version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/psql/data

  server:
    build:
      context: ../..
      dockerfile: build/package/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "3000:3000"
    environment:
      RDS_HOSTNAME: db
      RDS_DB_NAME: postgres
      RDS_PORT: 5432
      RDS_USERNAME: postgres
      RDS_PASSWORD: password
    restart: unless-stopped

volumes:
  db-data: